### ISSUE TITLE
_ completing input seems not working anymore

### ISSUE THREAD

**Issue by uggyuggy** [famasoon/crtsh#9] opened 2020-08-22 15:15 UTC
Hi,

Thank's for sharing your software!

It looks like the `_` completing input does not work anymore.
This is possibly due to a change on crt.sh side..
Here is the test from the README with `kaspe_sky.com`

```
 👉 crtsh -q kaspe_sky.com -o
 👉 
 👉 crtsh -q kaspersky.com -o | head -1 
maltegofe.kaspersky.com
 👉
```

Second test to show without `_` looks OK.

**Comment by famasoon** [comment] 2022-08-14 16:20
Thanks for feedback!
I find root cause, `json.Unmarshal` can not decode `_` .
So, I will fix it

**Comment by famasoon** [comment] 2022-08-14 17:11
```
if err = json.Unmarshal(res, &ctlogs); err != nil {
	if serr, ok := err.(*json.SyntaxError); ok {
		log.Println("Occurred at offset:", serr.Offset)
		return err
	}
}
```

I add ↑ code, and result 
```
❯ go run main.go -q kaspe%25.sky.com -o
2022/08/15 02:07:36 Occurred at offset: 2
2022/08/15 02:07:36 invalid character 'B' looking for beginning of value
exit status 1
```

It is  may not return json format? 🤔

**Comment by famasoon** [comment] 2022-08-14 17:12
```
❯ go run main.go -q kaspe%25.sky.com -o
[91 66 69 71 73 78 95 72 69 65 68 69 82 83 93 10 67 111 110 116 101 110 116 45 84 121 112 101 58 32 97 112 112 108 105 99 97 116 105 111 110 47 106 115 111 110 10 91 69 78 68 95 72 69 65 68 69 82 83 93 10 60 66 82 62 60 66 82 62 85 110 115 117 112 112 111 114 116 101 100 32 117 115 101 32 111 102 32 39 37 39 60 47 66 79 68 89 62 10 60 47 72 84 77 76 62 10]2022/08/15 01:51:54 invalid character 'B' looking for beginning of value
exit status 1
```

offset 2 = 66, it is 'B' in ascii code

**Comment by famasoon** [comment] 2022-08-16 16:35
`_` does not supported for wildcard in crtsh.
So, I will close this issue and archive this repository

**Comment by famasoon** [comment] 2022-08-16 17:04
Reopen
[Reason]
Help me 🙇

**Comment by famasoon** [comment] 2022-08-18 16:11
```
❯ go run main.go -q example.com -o
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
subjectname@example.com
subjectname@example.com
example.com
m.testexample.com
www.example.com
*.example.com
example.com
*.example.com
example.com
m.example.com
www.example.com
dev.example.com
example.com
products.example.com
support.example.com
www.example.com
example.com
www.example.com
example.com
www.example.com
```

hmm... can it run... 🤔

**Comment by famasoon** [comment] 2022-08-18 16:32
```
❯ go run main.go -q kaspe%sky.com -o
[BEGIN_HEADERS]
Content-Type: application/json
[END_HEADERS]
<BR><BR>Unsupported use of '%'</BODY>
</HTML>
```

May be `https://crt.sh` does not supported wildcard?

**Comment by famasoon** [comment] 2022-08-18 16:35
Currentry statys
1. `_` is not wildcard. `%` is wildcard now.
2. In just case, can not get cert logs which wildcard in the query.

**Comment by famasoon** [comment] 2022-08-18 16:51
In edge case
```
❯ go run main.go -q %25.example.com -o | sort | uniq
*.example.com
dev.example.com
example.com
m.example.com
m.testexample.com
products.example.com
subjectname@example.com
support.example.com
www.example.com
```

`%` is working in at the beginning.
I will update README
So this tool is `_` not working, please instead this approach.
Regards

**Comment by famasoon** [comment] 2022-08-19 16:39
The crt.sh specification has been changed.
Therefore, searches using _ are currently not possible.
The README has been updated accordingly.
https://github.com/famasoon/crtsh/pull/10
Regards,

**Closed as completed by famasoon** 2022-08-19 16:39 UTC
Labels: bug, help wanted, good first issue
